[versions]
compose-bom = "2024.09.00"
core-ktx = "1.13.1"
lifecycle-runtime-ktx = "2.8.6"
lifecycle-viewmodel-compose = "2.8.6"
activity-compose = "1.9.2"
navigation-compose = "2.8.0"
generativeai = "0.9.0"
firebase-vertexai = "16.5.0"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
firebase-vertexai = { group = "com.google.firebase", name = "firebase-vertexai", version.ref = "firebase-vertexai" }

[plugins]

android-application = { id = "com.android.application", version = "8.5.2" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.0.0" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.0.0" }